name: resistor
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_lints:
  resistor_package:
    git:
      url: 'https://github.com/HSayer44/resistor_package.git'
      ref: "master"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true